language: php
php:
  - 5.4
  - 5.5

 # Commands to be run before your environment runs.
before_script:
  - composer self-update

# allow_failures: Allow this build to fail under the specified environments.
matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5

# Customize when the notification emails are sent.
notifications:
    on_success: always
    on_failure: always